twig:
  default_path: "%kernel.project_dir%/templates"
  form_theme: "bootstrap_5_layout.html.twig"
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    cartService: "@App\\Service\\CartService"
    admin: "Geoffrey Vercaemer"

when@test:
  twig:
    strict_variables: true
